### ISSUE TITLE
Transformed image issue

### ISSUE THREAD

**Issue by VarunThapliyal23** [adrianhajdin/imaginify#20]
I've been facing an issue for not seeing the transformed image, after clicking on the "apply transformation" button the transformed image section keeps loading forever and doesn't shows the transformed image and by looking through inspect it shows these errors -

![image](https://github.com/adrianhajdin/ai_saas_app/assets/62562647/eb611538-3ad1-46c4-8935-ed90ce109fd0)
![image](https://github.com/adrianhajdin/ai_saas_app/assets/62562647/10fa585a-f34c-41e0-80cc-303bf2b82fdd)

but even if I try to save transformed image even without it showing on the screen by clicking the "save image" button the page loads to transformation page and the newly transformed image data also gets saved in my mongodb atlas database,

![image](https://github.com/adrianhajdin/ai_saas_app/assets/62562647/6d18b8e1-5208-4e53-8d4f-71be0f1fef32)

![image](https://github.com/adrianhajdin/ai_saas_app/assets/62562647/a589491b-47f0-47af-828c-1f3cf733981a)

So what exactly I am facing the issue and how can I fix it as I've already checked my code with the video

**Comment by WelldiusPrimeX** [comment]
i am also having this issue when i click apply transformation it just loads forever and eventually shows that logo that signifies the image didn't load, i wonder what the problem is? i have checked everything cant find out what the issue is, the console is also complaining that src and alt are missing.

**Comment by WelldiusPrimeX** [comment]
finally resolved it, in my own case the error was actually from my mediauploader.tsx file, my advice is for u to create a temporal file u will delete later paste the code from the official jsm github repo  mediauploader.tsx file in that file and use the vscode comparing file feature to check what u might have done wrong, if u didn't make mistake in that particular file u can check other files connected with the transformation feature and repeat same step of comparing to see where u might have made a mistake, i did that with a couple of files and i realized i made some typos in the mediauploader.tsx file but once i corrected it everything works as it should, hope this helps.

**Comment by VarunThapliyal23** [comment]
> finally resolved it, in my own case the error was actually from my mediauploader.tsx file, my advice is for u to create a temporal file u will delete later paste the code from the official jsm github repo mediauploader.tsx file in that file and use the vscode comparing file feature to check what u might have done wrong, if u didn't make mistake in that particular file u can check other files connected with the transformation feature and repeat same step of comparing to see where u might have made a mistake, i did that with a couple of files and i realized i made some typos in the mediauploader.tsx file but once i corrected it everything works as it should, hope this helps.

THANKS A LOT MATE!! I've finally resolved the issue just like you've said I had checked all the files connected to "TransformationForm.tsx" file by using vscode comparing file feature and finally found out that I had made a typo in the "TransformedImage.tsx" file and after fixing it I can now see the transformed Image on my project.
