### ISSUE TITLE
User not found 

### ISSUE THREAD

**Issue by aryanjotwani** [adrianhajdin/imaginify#25]
Unable to create users in the database.

Unhandled Runtime Error
Error: Error: User not found

Source
lib\utils.ts (18:11) @ handleError

  16 |     // This is a native JavaScript error (e.g., TypeError, RangeError)
  17 |     console.error(error.message);
> 18 |     throw new Error(`Error: ${error.message}`);
     |           ^
  19 |   } else if (typeof error === "string") {
  20 |     // This is a string error message
  21 |     console.error(error);

**Comment by atilla-the-hun** [comment]
Running into this same error. My app worked fine before, now I get this. Anyone found an answer to this?

**Comment by aryanjotwani** [comment]
use this middleware.ts
it worked for me.

import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";

const isPublicRoute = createRouteMatcher([
  "/sign-in(.*)",
  "/sign-up(.*)",
  "/api/webhooks(.*)",
  "/", "/api/webhooks/clerk", "/api/webhooks/stripe"
]);

export default clerkMiddleware((auth, request) => {
  if (!isPublicRoute(request)) {
    auth().protect();
  }
});

export const config = {
  matcher: ["/((?!.*\\..*|_next).*)", "/", "/(api|trpc)(.*)"],
};
