### ISSUE TITLE
clerk webhook failed user.created and sending  

### ISSUE THREAD

**Issue by iamrahul-14** [adrianhajdin/imaginify#4]
![Screenshot 2024-02-21 182230](https://github.com/adrianhajdin/ai_saas_app/assets/153355094/92d1427a-50af-4203-85b5-74977702dc8b)

**Comment by Zaidbhati10114** [comment]
me too getting same error .
has anyone resolved this error ?

**Comment by Zaidbhati10114** [comment]
@iamrahul-14  did you solved this error ?

**Comment by iamrahul-14** [comment]
>  @iamrahul-14  did you solved this error ? 
> 

Nope

**Comment by panu2109** [comment]
> > @iamrahul-14  did you solved this error ?
> 
> Nope

any solution bro?

**Comment by panu2109** [comment]
> @iamrahul-14 did you solved this error ?

did u manage to solve it bro

**Comment by Zaidbhati10114** [comment]
> > @iamrahul-14 did you solved this error ?
> 
> did u manage to solve it bro

yes i have solved please share you're vercel logs i'' try to solve yours.

**Comment by panu2109** [comment]
brother i have clone the project..did u..followed the whole tutorial from starting please reply me its urgent...if possible can u share me u r insta handle..so i can ask you doubt regarding this pleasee reply..

**Comment by panu2109** [comment]
> > > @iamrahul-14 did you solved this error ?
> > 
> > 
> > did u manage to solve it bro
> 
> yes i have solved please share you're vercel logs i'' try to solve yours.

please take a look i have my send u the msg on insta please reply my username pranitmankar21

**Comment by panu2109** [comment]
> > > @iamrahul-14 did you solved this error ?
> > 
> > 
> > did u manage to solve it bro
> 
> yes i have solved please share you're vercel logs i'' try to solve yours.

![Screenshot (80)](https://github.com/adrianhajdin/ai_saas_app/assets/159440419/9e127076-3575-44e4-a8de-b033accaa15c)
please check out...i want to submit  my project tomorrow u clg please help me bro

**Comment by Zaidbhati10114** [comment]
> > > > @iamrahul-14 did you solved this error ?
> > > 
> > > 
> > > did u manage to solve it bro
> > 
> > 
> > yes i have solved please share you're vercel logs i'' try to solve yours.
> 
if you have cloned it i can't help you bro

**Comment by Zaidbhati10114** [comment]
follow the process you can complete it till tomorrow

**Comment by panu2109** [comment]
> follow the process you can complete it till tomorrow

bro are u sure about it??

**Comment by Zaidbhati10114** [comment]
Yes

**Comment by panu2109** [comment]
> > follow the process you can complete it till tomorrow
> 
> bro are u sure about it??if i follow al the st

> Yes

please can u connect me through your insta it will help me a lot..

**Comment by panu2109** [comment]
i just want to ask some queries related to this project..

**Comment by panu2109** [comment]
> follow the process you can complete it till tomorrow

bro if all the steps properly...step by step it will get complete naa..???

**Comment by Zaidbhati10114** [comment]
yes follow the process

**Comment by panu2109** [comment]
> yes follow the process

okayy brooo tysm i was scared so much..how many hours did it take u to complete the project

**Comment by iamrahul-14** [comment]
heyy can you please help

**Comment by panu2109** [comment]
> heyy can you please help

did you followed the steps or cloned the project

**Comment by iamrahul-14** [comment]
> > heyy can you please help
> 
> did you followed the steps or cloned the project

i have followed the steps

**Comment by Zaidbhati10114** [comment]
Follow the steps you can complete the project

**Comment by panu2109** [comment]
> Follow the steps you can complete the project

bro rahul has followed all the steps then to is facing the issue

**Comment by Zaidbhati10114** [comment]
> > Follow the steps you can complete the project
> 
> bro rahul has followed all the steps then to is facing the issue
whats the error ?

**Comment by panu2109** [comment]
> [Zaidbhati10114](/Zaidbhati10114)

same error which he posted at first

**Comment by panu2109** [comment]
> ![Screenshot 2024-02-21 182230](https://private-user-images.githubusercontent.com/153355094/306628807-92d1427a-50af-4203-85b5-74977702dc8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDc4NjIsIm5iZiI6MTcwODYwNzU2MiwicGF0aCI6Ii8xNTMzNTUwOTQvMzA2NjI4ODA3LTkyZDE0MjdhLTUwYWYtNDIwMy04NWI1LTc0OTc3NzAyZGM4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxMzEyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzA5ZjJlYmI0NTNhZWEwNzM0M2MzNmU2ODFmMmU5OWE3ZmM3NmM3ZDljM2JjZTVhMzY0OWU3YmUyMjdlYzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aJDJc3jmbwPHF6yyhqmZgVPoPYV2L9Vqn_IvSNhSSpM)

this one bro

**Comment by Zaidbhati10114** [comment]
this soln only works if you followed the process 
check the webhooks url in clerk website is it correct
also check mongodb url is correct means the username and password 
or create new mongodb project and do the process again 
by this my issue was resolved

**Comment by panu2109** [comment]
> this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolved

the same issue was redirecting to you bro?

**Comment by iamrahul-14** [comment]
> this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolved

i have done this for 4 th time but till getting error

**Comment by Zaidbhati10114** [comment]
> > this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolved
> 
> i have done this for 4 th time but till getting error

show me youre vercel logs and clerk logs

**Comment by iamrahul-14** [comment]
> Zaidbhati10114

i have deleted everything. Now i have to do it from starting on words can you send your instagram id so that we can communicate there.

**Comment by iharshitjaiswal** [comment]
> > this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolved
> 
> i have done this for 4 th time but till getting error

i am also facing the same issue but not able to resolve it.
followed all the steps

**Comment by iamrahul-14** [comment]
![IMG-20240222-WA0020.jpg](https://github.com/adrianhajdin/ai_saas_app/assets/153355094/1d254c41-9e56-4a91-ae19-0520a8d9b027)

![IMG-20240222-WA0018.jpg](https://github.com/adrianhajdin/ai_saas_app/assets/153355094/7144d3bd-fb2e-47dd-bc71-0a8e36b9804c)

![IMG_20240222_230239.jpg](https://github.com/adrianhajdin/ai_saas_app/assets/153355094/b6825a68-f7bc-46dc-b32e-767dcadabf77)

**Comment by iamrahul-14** [comment]
![Screenshot 2024-02-22 233633](https://github.com/adrianhajdin/ai_saas_app/assets/153355094/592992ac-db37-4fd1-85cb-e819d640666e)
![Screenshot 2024-02-22 233701](https://github.com/adrianhajdin/ai_saas_app/assets/153355094/3f2124e8-38b6-4a73-8fe3-6a9267a92635)

**Comment by Ishuboi07** [comment]
![2022-02-02 (1)](https://github.com/adrianhajdin/ai_saas_app/assets/123348813/0bbd130e-7256-4fb2-ad39-38e6ebfbeeff)
![Screenshot 2024-02-23 113502](https://github.com/adrianhajdin/ai_saas_app/assets/123348813/5c8f1de6-55de-46e8-9aa9-1873f48154d2)
![Screenshot 2024-02-23 113557](https://github.com/adrianhajdin/ai_saas_app/assets/123348813/85cc6db3-2c17-4b9a-b475-9347850affe3)


Please solve my issue here is my vercel and clerk logs

**Comment by iamishaanagarwal** [comment]
![Screenshot 2024-02-23 113502](https://github.com/adrianhajdin/ai_saas_app/assets/123348813/c869f3f1-41bb-4f04-9db9-edae6c67611d)
![Screenshot 2024-02-23 113557](https://github.com/adrianhajdin/ai_saas_app/assets/123348813/14bfbe88-e673-4ac0-8068-5c9188a1d61c)

please resolve my error here are my vercel and clerk logs

**Comment by rahulgore7** [comment]
Did anyone resolved it? I am too facing the same issue. I am attaching my vercel logs. And one more question: Did you keep the '<''>' symbol in mongodb password or not?
![Screenshot 2024-02-23 205352](https://github.com/adrianhajdin/ai_saas_app/assets/107752614/da125414-4a99-4ac2-93b7-f2d81b13537e)

**Comment by ghost** [comment]
I fixed mine how i did it
**Follow this code**

1. Go to, "lib/database/mongoose.ts" 
![image](https://github.com/adrianhajdin/ai_saas_app/assets/59811681/16c034b2-a716-4acc-8b5c-8eaa94019e83)

2. Go to, "middleware.ts"
![image](https://github.com/adrianhajdin/ai_saas_app/assets/59811681/0f35f740-68d5-4311-bced-317d7706ec8a)

**Comment by panu2109** [comment]
![error1-vercel](https://github.com/adrianhajdin/ai_saas_app/assets/159440419/02fced8c-35ce-4e95-a5d7-87193d28ad72)
please help me rahul and zaid

**Comment by panu2109** [comment]
![clerk(errror)-2](https://github.com/adrianhajdin/ai_saas_app/assets/159440419/d2bfb69d-20a1-4e8f-a904-525a76c0e7cc)
@iamrahul-14   @Zaidbhati10114

**Comment by Zaidbhati10114** [comment]
Click on vercel log error send the error in details please

**Comment by panu2109** [comment]
> Click on vercel log error send the error in details please

okay
![3](https://github.com/adrianhajdin/ai_saas_app/assets/159440419/b2e99824-9381-4be8-a044-b44f3e50993c)
![Uploading 4.png…]()

**Comment by Zaidbhati10114** [comment]
this soln only works if you followed the process
check the webhooks url in clerk website is it correct
also check mongodb url is correct means the username and password
or create new mongodb project and do the process again
by this my issue was resolved

**Comment by panu2109** [comment]
> this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolved

okayy

**Comment by panu2109** [comment]
> this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolv

> this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolved

the paswd of mongodb should be in <..> ??

**Comment by Zaidbhati10114** [comment]
> > this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolv
> 
> > this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolved
> 
> the paswd of mongodb should be in <..> ??

no follow the env file format mentioned in the video

**Comment by panu2109** [comment]
> > > this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolv
> > 
> > 
> > > this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolved
> > 
> > 
> > the paswd of mongodb should be in <..> ??
> 
> no follow the env file format mentioned in the video

okay

**Comment by panu2109** [comment]
> > > this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolv
> > 
> > 
> > > this soln only works if you followed the process check the webhooks url in clerk website is it correct also check mongodb url is correct means the username and password or create new mongodb project and do the process again by this my issue was resolved
> > 
> > 
> > the paswd of mongodb should be in <..> ??
> 
> no follow the env file format mentioned in the video

bro can u share ur env file on insta?
