### ISSUE TITLE
i wnt help

### ISSUE THREAD

**Issue by ghost** [adrianhajdin/imaginify#5]
![image](https://github.com/adrianhajdin/ai_saas_app/assets/84471237/e1103f02-527e-453e-b317-e1b13500d1a0)

**Comment by panu2109** [comment]
same issue

**Comment by Anuj092** [comment]
I have also same error but I fix now.

**Comment by ghost** [comment]
> I have also same error but I fix now.

can you help me
how i can fix

**Comment by iamrahul-14** [comment]
> I have also same error but I fix now.

how did uh fix it can you me please
