### ISSUE TITLE
how i can fix

### ISSUE THREAD

**Issue by ghost** [adrianhajdin/imaginify#6]
![image](https://github.com/adrianhajdin/ai_saas_app/assets/84471237/734d4f45-5155-4110-87f3-8c0097f293d0)

**Comment by panu2109** [comment]
bro did u fix it??
cause i am facing the same issue

**Comment by McFlanky** [comment]
i have same errot too exact same one

**Comment by Madhannmady07** [comment]
> ![image](https://private-user-images.githubusercontent.com/84471237/306940915-734d4f45-5155-4110-87f3-8c0097f293d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTExMTksIm5iZiI6MTcwODc1MDgxOSwicGF0aCI6Ii84NDQ3MTIzNy8zMDY5NDA5MTUtNzM0ZDRmNDUtNTE1NS00MTEwLTg3ZjMtOGMwMDk3ZjI5M2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA1MDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5OWM4ZDU1MjU0NjM5NzRkMGE2YTM4M2Y5MDMyY2VlMjk2ODU5Y2JjYzc5YTQ4ZmJhZDU4ZWViOTIxN2Y4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1UOOi2mBzLGUoNFOq9X2S3183MbZpUPb5SJ_lrA5Zgk)

Check  your MongoDB , that is there any objects (data) getting passed from clerk correctly , i mean if u signed in and coded properly , u will see data along with the objects in your mongodb collections , 


If u have this part correct , u will not get any errors ...

**Comment by McFlanky** [comment]
i fixed it i had an imagechema error and i was missing a word in a file my bad

**Comment by ghost** [comment]
> i fixed it i had an imagechema error and i was missing a word in a file my bad

tell me brother
